server:
  port: 8099
# mysql
spring:
  datasource:
    # 数据源配置只需修改IP、端口、用户名和密码
    driver-class-name: com.mysql.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT}
    username: ${SPRING_DATASOURCE_USERNAME:hand}
    password: ${SPRING_DATASOURCE_PASSWORD:handhand}

#    driver-class-name: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521:helowin}
#    username: ${SPRING_DATASOURCE_USERNAME:system}
#    password: ${SPRING_DATASOURCE_PASSWORD:manager}

installer:
  dataDir: init-data
  groovyDir: groovy
data:
  version: 1.4
